### ISSUE TITLE
Print line numbers when complaining about errors

### ISSUE THREAD

**Issue by rschwietzke** [Xceptance/testsuite-nocoding#14]
Try to print YAML line numbers when complaining or failing. Greatly helps debugging.

**Comment by matthiasware** [comment]
This is possible if we change the whole parsing process of our yaml file.
So far, the parser returns a huge hashmap without any line references .
Right now we have only line references when the parser detects syntax errors.

**Comment by ckeiner** [comment]
Since the YAML parsing process was reworked, the line numbers are shown in most cases.
It may not be shown correctly if the key is an alias and the corresponding value contains an error.
For example, see the following error of [complexReferenceParsing](https://github.com/Xceptance/xlt-nocoding/blob/9e41b89915fcf2c4e23a201a165ed3684dfec178/src/test/java/com/xceptance/xlt/nocoding/parser/yaml/YamlReferencesTest.java#L51-L55):

![image](https://user-images.githubusercontent.com/27275355/53335197-229a6000-38fb-11e9-925e-91e4d3d49ea5.png)

In such cases, we cannot easily know that an alias was used. Since it also doesn't make much sense to replace keys with an alias for our reduced set of keywords, we decided to not offer support for keys that are an alias, or at least not for now. If this feature is requested regardless, please open a new issue.

For every other case, [commit 95f79fe8e8ac0f0db306582e859a3e3f8f744b70](https://github.com/Xceptance/xlt-nocoding/tree/95f79fe8e8ac0f0db306582e859a3e3f8f744b70) changed every YAML parsing test case so they verify that the correct line number is shown in the error message.
